In [15]:
import pandas as pd
import numpy as np

In [20]:
# N° 2

mylist = list('abcedfghijklmnopqrstuvwxyz')  # Criando uma lista
myarr = np.arange(26)   # Criando um array, até 25 (26-1)
mydict = dict(zip(mylist,myarr))   # 'Concatenando' lista e array em um dicionário (zip forma pares de valores), precisa do dict

In [ ]:
a = pd.Series(mylist, name='alpha')   # Criando uma Series a partir da lista
b = pd.Series(myarr)   # Criando uma Series a partir do array
c = pd.Series(mydict)  # Criando uma Series a partir da 'concatenação' (primeiro valor passado se torna o index)

In [20]:
# N° 3

ser3 = pd.DataFrame(c).reset_index()   # Criando um novo index para o DF

In [28]:
# N° 4

d = pd.concat([a,b], axis=1)  # Combinando Series para formar um DF (axis=1, para colunas)
d

alpha   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

In [31]:
# N° 5

a.name   # Retorna o nome da coluna

'alpha'

In [33]:
# N° 6

ser1 = pd.Series([1,2,3,4,5])
ser2 = pd.Series([4,5,6,7,8])

In [37]:
a = ser1[~ser1.isin(ser2)]  # Retorna os valores de ser1 que não estão presentes em ser2 (~ para negação)

In [39]:
b = ser2[~ser2.isin(ser1)]   # Retorna os valores de ser2 que não estão presentes em ser1 (~ para negação)

In [41]:
pd.concat([a,b]) # 'Concatenando' os valores de a,b

0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64

In [2]:
# N° 8

ser = pd.Series(np.random.normal(10,5,25))
ser.describe()    # Retorna uma descrição completa de valores(máximo, mínimo, média, 25th percentil e etc...)

count    25.000000
mean     11.551783
std       4.394091
min       1.856239
25%       9.341803
50%      11.105352
75%      14.489853
max      19.005285
dtype: float64

In [46]:
a = np.array(ser.describe()).round(2)  # Retorna um array, arredondando os valores do describe
a

array([25.  ,  9.72,  5.18, -0.75,  6.62,  9.  , 11.88, 22.48])

In [47]:
a[3:]   # Retorna os valores de 3 em diante (:)

array([-0.75,  6.62,  9.  , 11.88, 22.48])

In [3]:
v = np.percentile(ser,25) # Destacando valor de percentis da series (25 = 25%) (50 = 50%) (75 = 75%)
v

9.341802967414226

In [4]:
# N° 9

ser = pd.Series(np.take(list('abcdefgh'),np.random.randint(8,size=30)))
ser     # randint gerando uma matriz com a lista passada de tamanho 30

0     f
1     g
2     a
3     f
4     b
5     d
6     a
7     d
8     c
9     f
10    b
11    b
12    b
13    g
14    g
15    g
16    h
17    g
18    c
19    f
20    g
21    e
22    c
23    h
24    c
25    g
26    c
27    h
28    g
29    a
dtype: object

In [61]:
x = ser.value_counts()  # Retorna a frequência de valores na Series
x

d    7
f    5
a    5
g    3
h    3
c    3
e    2
b    2
dtype: int64

In [62]:
# N° 10

ser[ser.isin(x[x<5].index)] = 'other'  # Substituindo por 'other', os valores de frequência menores que 5 com o índice
ser

0     other
1         f
2         a
3         d
4     other
5     other
6         d
7     other
8         d
9         d
10        a
11        f
12    other
13        d
14    other
15        d
16        f
17    other
18        f
19        d
20    other
21        a
22        a
23    other
24    other
25    other
26        a
27    other
28        f
29    other
dtype: object

In [63]:
# N° 12

ser = pd.Series(np.random.randint(1,10,35)) # Números aleatórios entre 1 e 10, 35 vezes
ser

0     7
1     8
2     7
3     3
4     9
5     4
6     1
7     9
8     8
9     1
10    5
11    6
12    5
13    6
14    5
15    6
16    7
17    9
18    6
19    5
20    8
21    4
22    3
23    8
24    1
25    3
26    7
27    1
28    7
29    3
30    5
31    3
32    1
33    4
34    4
dtype: int32

In [65]:
a = np.array(ser).reshape(7,5) # Convertendo uma Series em um array, para funcionar o reshape
a                              # A Series tem 35 elementos, logo o formato do array tem que ser 35 (7x5=35)

array([[7, 8, 7, 3, 9],
       [4, 1, 9, 8, 1],
       [5, 6, 5, 6, 5],
       [6, 7, 9, 6, 5],
       [8, 4, 3, 8, 1],
       [3, 7, 1, 7, 3],
       [5, 3, 1, 4, 4]])

In [67]:
df = pd.DataFrame(a)   # Transformando o array num DF
df

0  1  2  3  4
0  7  8  7  3  9
1  4  1  9  8  1
2  5  6  5  6  5
3  6  7  9  6  5
4  8  4  3  8  1
5  3  7  1  7  3
6  5  3  1  4  4

In [81]:
# N° 13

ser2 = pd.Series(np.random.randint(1,10,7))
ser2

0    3
1    9
2    2
3    9
4    1
5    3
6    2
dtype: int32

In [82]:
ser2[(ser2%3)==0].index  # Retorna a posição dos múltiplos de 3 na Series

Int64Index([0, 1, 3, 5], dtype='int64')

In [84]:
# N° 14

ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

In [85]:
ser.take([0, 4, 8, 14, 20])  # Extraindo valores através da posição na Series

0     a
4     e
8     i
14    o
20    u
dtype: object

In [86]:
ser.iloc[[0, 4, 8, 14, 20]]

0     a
4     e
8     i
14    o
20    u
dtype: object

In [87]:
# N° 16

ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

In [90]:
ser1[ser1.isin(ser2)].index   # Retorna a posição dos valores de ser1, também presentes em ser2 (posição em ser1)

Int64Index([0, 4, 5, 8], dtype='int64')

In [34]:
# N° 18

ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [36]:
b = ser.map(lambda x: x.title()) # Retornando as primeiras letras da series Maiúsculas
b

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [35]:
ser.str.title() 

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [138]:
# N° 19

c = ser.map(lambda x: len(x)) # Retorna to tamanho das strings em cada linha
c

0    3
1    2
2    4
3    4
dtype: int64

In [3]:
# N° 20

ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

In [4]:
ser1 = ser.diff().tolist() # Diferença entre os valores da Series, tolist() para computar em uma lista
ser1

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]

In [8]:
ser2 = ser.diff().diff().tolist() # Diferença da diferença
ser2

[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]

In [7]:
# N° 21

ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
ser

0         01 Jan 2010
1          02-02-2011
2            20120303
3          2013/04/04
4          2014-05-05
5    2015-06-06T12:20
dtype: object

In [8]:
ser1 = pd.to_datetime(ser) # Convertendo uma series 'object', em data (to_datetime())
ser1

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [9]:
# N° 22
from datetime import date
ser1.loc[0].week  # Selecionando a semana do ano na data especificada pelo índice

53

In [10]:
ser1.dt.weekofyear # Retornando a semana de todas as datas

C:\Users\pfagu\AppData\Local\Temp\ipykernel_21496\3448958860.py:1: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  ser1.dt.weekofyear # Retornando a semana de todas as datas


0    53
1     5
2     9
3    14
4    19
5    23
dtype: int64

In [11]:
ser1.dt.day_of_year # Retornando os dias do ano, nas datas epecificadas

0      1
1     33
2     63
3     94
4    125
5    157
dtype: int64

In [157]:
# N° 23

ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
ser

0    Jan 2010
1    Feb 2011
2    Mar 2012
dtype: object

In [13]:
a = ser.map(lambda x: x + ' 04') # Adicionando 'dia', através de um lambda (map para fazer em toda Series)
a.map(lambda x : x.replace(' ','-')) # Substituíndo 'espaço' por hífen

0    Jan-2010-04
1    Feb-2011-04
2    Mar-2012-04
dtype: object

In [14]:
# N° 24

import re
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
ser

0     Apple
1    Orange
2      Plan
3    Python
4     Money
dtype: object

In [17]:
# Filtrando palavras numa Series, que contenham mais de uma vogal
# re.findall para 'procurar' as vogais pela Series
# x.lower para 'procurar' as palavras que contenham também duas ou mais vogais minúsculas

[x for x in ser if (len(re.findall('[aeiou]',x.lower())) >=2)]

['Apple', 'Orange', 'Money']

In [18]:
[re.findall('[aeiouAEIOU]',x)for x in ser] # Extraindo as vogais de cada palavra de uma Series, maíusculas e minúsculas

[['A', 'e'], ['O', 'a', 'e'], ['a'], ['o'], ['o', 'e']]

In [10]:
# N° 25 

emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com','rameses'])

In [11]:
import re # Importando a biblioteca de regular expressions (regex)

In [14]:
emails[emails.str.match(r'[A-Za-z0-9._]+@[A-Za-z0-9]+\.[com]')] # Estudar as siglas do regex

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object

In [13]:
# N° 26

fruta = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10)) # Escolher aleatóriamente as 'frutas' 10 vezes
peso = pd.Series(np.linspace(1, 10, 10)) # Gerar 10 números no intervalo de 1 à 10
teste = pd.Series(np.random.randint(3,15,10)) # Gerar números aleatórios de 3 à 15, 10 vezes

In [3]:
fruta

0     apple
1    banana
2    carrot
3    carrot
4     apple
5     apple
6     apple
7    carrot
8     apple
9    banana
dtype: object

In [4]:
ser = pd.concat([fruta, peso, teste], axis=1) # Usando concat para unir as Series num DF
ser.columns = ['fruta', 'peso', 'teste'] # Dando nomes às colunas
ser

fruta  peso  teste
0   apple   1.0      3
1  banana   2.0      4
2  carrot   3.0     14
3  carrot   4.0      8
4   apple   5.0      7
5   apple   6.0     14
6   apple   7.0      8
7  carrot   8.0      8
8   apple   9.0      6
9  banana  10.0      3

In [5]:
# Agrupando pela coluna 'fruta' para retornar a média das colunas 'peso' e 'teste'
# Este método funciona quando é necessário para mais de uma coluna

media = ser.groupby('fruta')[['peso','teste']] 
media.mean()

peso  teste
fruta              
apple    5.6    7.6
banana   6.0    3.5
carrot   5.0   10.0

In [6]:
# Método alternativo, com valores de apenas uma coluna

ser.groupby('fruta').agg(media=('peso', np.mean)).reset_index()

fruta  media
0   apple    5.6
1  banana    6.0
2  carrot    5.0

In [9]:
# Outro método alternativo
# Passar o nome da coluna desejada antes do agg

ser.groupby(['fruta']).peso.agg([np.mean]).reset_index()

fruta  mean
0   apple   5.6
1  banana   6.0
2  carrot   5.0

In [136]:
# N° 27

p = pd.Series([1,2,3,4,5,6,7,8,9,10])
q = pd.Series([10,9,8,7,6,5,4,3,2,1])

In [165]:
# Cálculando a distância euclidiana (distância entre dois pontos), sem biblioteca

dist = np.sum(np.square(p - q)) 
print(np.sqrt(dist)) 

18.16590212458495


In [138]:
# Com bilioteca

dist_1 = np.linalg.norm(p - q) 
print(dist_1)

18.16590212458495


In [11]:
# N° 28

ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

In [12]:
from scipy.signal import find_peaks

In [14]:
local_max_idx, _= find_peaks(ser)
local_max = ser[local_max_idx]   # Identificando os picos (peaks) dentro da Series

In [15]:
local_max

1    10
5    10
7     7
dtype: int64

In [47]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Manufacturer        89 non-null     object 
 1   Model               92 non-null     object 
 2   Type                90 non-null     object 
 3   Min.Price           86 non-null     float64
 4   Price               91 non-null     float64
 5   Max.Price           88 non-null     float64
 6   MPG.city            84 non-null     float64
 7   MPG.highway         91 non-null     float64
 8   AirBags             87 non-null     object 
 9   DriveTrain          86 non-null     object 
 10  Cylinders           88 non-null     object 
 11  EngineSize          91 non-null     float64
 12  Horsepower          86 non-null     float64
 13  RPM                 90 non-null     float64
 14  Rev.per.mile        87 non-null     float64
 15  Man.trans.avail     88 non-null     object 
 16  Fuel.tank.

In [48]:
# N° 29

my_str = 'dbc deb abed gade'
my_str

'dbc deb abed gade'

In [54]:
# A função re.findall() retorna todas as correspondências não sobrepostas de um padrão em uma string.
# A função retorna todas as descobertas como uma lista. A pesquisa ocorre da esquerda para a direita.

b = re.findall('[a-z]',my_str)
b

['d', 'b', 'c', 'd', 'e', 'b', 'a', 'b', 'e', 'd', 'g', 'a', 'd', 'e']

In [57]:
c = pd.Series(b) # Transformar o re.findall(), numa Series para fazer as operações
c

0     d
1     b
2     c
3     d
4     e
5     b
6     a
7     b
8     e
9     d
10    g
11    a
12    d
13    e
dtype: object

In [58]:
c.value_counts() # Retornando a frequência dos valores

d    4
b    3
e    3
a    2
c    1
g    1
dtype: int64

In [59]:
my_str.replace(' ','c') # Substituíndo os espaços vazios pela letra menos frequente

'dbccdebcabedcgade'

In [61]:
# N° 30

ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
ser  # Adicionando 10 sábados a partir da data especificada, junto com números aleatórios

2000-01-01    7
2000-01-08    3
2000-01-15    9
2000-01-22    8
2000-01-29    1
2000-02-05    2
2000-02-12    8
2000-02-19    7
2000-02-26    1
2000-03-04    4
Freq: W-SAT, dtype: int32

In [11]:
# N° 31

ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
ser   # Criando uma Series onde o índice são as datas

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64

In [13]:
# Preenchendo os índices (datas) somando 1 dia ('D') e preenchendo os valores com o valor da data anterior ('ffill')
# Resample + ffill, só funciona quando as datas são index

ser.resample('D').fillna(method='ffill')

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

In [19]:
ser.resample('D').ffill() # Pode ser passado diretamente com '.ffill()'

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

In [11]:
# N° 32

ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
ser

0      1.217606
1    -13.216833
2     -1.851966
3     -5.154189
4      0.810843
5      8.847881
6      8.335818
7    -11.161364
8      2.051763
9      3.437306
10     5.873981
11    11.617506
12    45.262035
13    24.329989
14    -9.932365
15    11.661396
16    19.784945
17    16.118970
18    16.765662
19    24.052750
dtype: float64

In [12]:
ser.autocorr() # Autocorrelação de toda Series

0.39939306767430455

In [13]:
# Fazendo um loop das autocorrelações entre os 10 primeiros elementos da Series

corr = [ser.autocorr(i).round(2) for i in range(11)]
corr

[1.0, 0.4, -0.02, 0.18, 0.21, -0.02, 0.38, 0.55, 0.21, -0.27, -0.05]

In [15]:
np.argmax(np.abs(corr[1:]))+1 # Retornando a posição do maior valor de 'corr', a partir da posicão 1...

7

In [17]:
np.argmax(corr[1:])+1

7

In [12]:
# N° 34

a = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')
a.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [13]:
# Alterando os valores da coluna 'medv', através de um apply com uma função lambda

a['medv'] = a['medv'].apply(lambda x: 'low' if x<25 else 'high')
a.head(5)

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98   low  
1  396.90   9.14   low  
2  392.83   4.03  high  
3  394.63   2.94  high  
4  396.90   5.33  high

In [14]:
# Alterando os valores de uma coluna, usando como parâmetro outra coluna do df

a['nox'] = a['medv'].apply(lambda x: 'a' if x=='low' else 'b')
a.head(5)

crim    zn  indus  chas nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0   a  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0   a  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0   b  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0   b  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0   b  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98   low  
1  396.90   9.14   low  
2  392.83   4.03  high  
3  394.63   2.94  high  
4  396.90   5.33  high

In [15]:
# N° 35

L = pd.Series('Aprender ciencia de dados é muito legal mas é difícil'.split(' '))
L

0    Aprender
1     ciencia
2          de
3       dados
4           é
5       muito
6       legal
7         mas
8           é
9     difícil
dtype: object

In [18]:
l = [] # Criando uma lista vazia, para fazer append dentro do laço for
for i in range(0, len(L), 2): # Laço for com range passo 0, tamanho da Series, de 2 em 2
    if len(L.iloc[i:])>=4: # Se o len(puxando pelos índices), for maior ou igual a 4 
        l.append(L.iloc[i:i+4].values) # adiciona os valores(i+4) a lista
    else:
        break
pd.DataFrame(l)

0        1      2        3
0  Aprender  ciencia     de    dados
1        de    dados      é    muito
2         é    muito  legal      mas
3     legal      mas      é  difícil

In [14]:
# N° 37

teste = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [22]:
teste.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Manufacturer        89 non-null     object 
 1   Model               92 non-null     object 
 2   Type                90 non-null     object 
 3   Min.Price           86 non-null     float64
 4   Price               91 non-null     float64
 5   Max.Price           88 non-null     float64
 6   MPG.city            84 non-null     float64
 7   MPG.highway         91 non-null     float64
 8   AirBags             87 non-null     object 
 9   DriveTrain          86 non-null     object 
 10  Cylinders           88 non-null     object 
 11  EngineSize          91 non-null     float64
 12  Horsepower          86 non-null     float64
 13  RPM                 90 non-null     float64
 14  Rev.per.mile        87 non-null     float64
 15  Man.trans.avail     88 non-null     object 
 16  Fuel.tank.

In [23]:
teste.describe() # Estatística descritiva do Df

Min.Price      Price  Max.Price   MPG.city  MPG.highway  EngineSize  \
count  86.000000  91.000000  88.000000  84.000000    91.000000   91.000000   
mean   17.118605  19.616484  21.459091  22.404762    29.065934    2.658242   
std     8.828290   9.724280  10.696563   5.841520     5.370293    1.045845   
min     6.700000   7.400000   7.900000  15.000000    20.000000    1.000000   
25%    10.825000  12.350000  14.575000  18.000000    26.000000    1.800000   
50%    14.600000  17.700000  19.150000  21.000000    28.000000    2.300000   
75%    20.250000  23.500000  24.825000  25.000000    31.000000    3.250000   
max    45.400000  61.900000  80.000000  46.000000    50.000000    5.700000   

       Horsepower          RPM  Rev.per.mile  Fuel.tank.capacity  Passengers  \
count   86.000000    90.000000     87.000000           85.000000   91.000000   
mean   144.000000  5276.666667   2355.000000           16.683529    5.076923   
std     53.455204   605.554811    486.916616            3.375748    1.045953   
min     55.000000  3800.000000   1320.000000            9.200000    2.000000   
25%    100.750000  4800.000000   2017.500000           14.500000    4.000000   
50%    140.000000  5200.000000   2360.000000           16.500000    5.000000   
75%    170.000000  5787.500000   2565.000000           19.000000    6.000000   
max    300.000000  6500.000000   3755.000000           27.000000    8.000000   

           Length   Wheelbase      Width  Turn.circle  Rear.seat.room  \
count   89.000000   92.000000  87.000000    88.000000       89.000000   
mean   182.865169  103.956522  69.448276    38.954545       27.853933   
std     14.792651    6.856317   3.778023     3.304157        3.018129   
min    141.000000   90.000000  60.000000    32.000000       19.000000   
25%    174.000000   98.000000  67.000000    36.000000       26.000000   
50%    181.000000  103.000000  69.000000    39.000000       27.500000   
75%    192.000000  110.000000  72.000000    42.000000       30.000000   
max    219.000000  119.000000  78.000000    45.000000       36.000000   

       Luggage.room       Weight  
count     74.000000    86.000000  
mean      13.986486  3104.593023  
std        3.120824   600.129993  
min        6.000000  1695.000000  
25%       12.000000  2647.500000  
50%       14.000000  3085.000000  
75%       16.000000  3567.500000  
max       22.000000  4105.000000

In [24]:
teste.describe().T # Forma transposta

count         mean         std     min       25%      50%  \
Min.Price            86.0    17.118605    8.828290     6.7    10.825    14.60   
Price                91.0    19.616484    9.724280     7.4    12.350    17.70   
Max.Price            88.0    21.459091   10.696563     7.9    14.575    19.15   
MPG.city             84.0    22.404762    5.841520    15.0    18.000    21.00   
MPG.highway          91.0    29.065934    5.370293    20.0    26.000    28.00   
EngineSize           91.0     2.658242    1.045845     1.0     1.800     2.30   
Horsepower           86.0   144.000000   53.455204    55.0   100.750   140.00   
RPM                  90.0  5276.666667  605.554811  3800.0  4800.000  5200.00   
Rev.per.mile         87.0  2355.000000  486.916616  1320.0  2017.500  2360.00   
Fuel.tank.capacity   85.0    16.683529    3.375748     9.2    14.500    16.50   
Passengers           91.0     5.076923    1.045953     2.0     4.000     5.00   
Length               89.0   182.865169   14.792651   141.0   174.000   181.00   
Wheelbase            92.0   103.956522    6.856317    90.0    98.000   103.00   
Width                87.0    69.448276    3.778023    60.0    67.000    69.00   
Turn.circle          88.0    38.954545    3.304157    32.0    36.000    39.00   
Rear.seat.room       89.0    27.853933    3.018129    19.0    26.000    27.50   
Luggage.room         74.0    13.986486    3.120824     6.0    12.000    14.00   
Weight               86.0  3104.593023  600.129993  1695.0  2647.500  3085.00   

                         75%     max  
Min.Price             20.250    45.4  
Price                 23.500    61.9  
Max.Price             24.825    80.0  
MPG.city              25.000    46.0  
MPG.highway           31.000    50.0  
EngineSize             3.250     5.7  
Horsepower           170.000   300.0  
RPM                 5787.500  6500.0  
Rev.per.mile        2565.000  3755.0  
Fuel.tank.capacity    19.000    27.0  
Passengers             6.000     8.0  
Length               192.000   219.0  
Wheelbase            110.000   119.0  
Width                 72.000    78.0  
Turn.circle           42.000    45.0  
Rear.seat.room        30.000    36.0  
Luggage.room          16.000    22.0  
Weight              3567.500  4105.0

In [26]:
# N° 38

np.argmax(teste['Price']) # Retorna o número da linha que contém o maior valor da coluna "Price"
                          # Este código para retornar o índice

58

In [15]:
teste['Price'].max() # Este código para retornar o valor em si, sem ser o índice

61.9

In [28]:
teste.iloc[58] # Retornando todos os valores da linha 58

Manufacturer               Mercedes-Benz
Model                               300E
Type                             Midsize
Min.Price                           43.8
Price                               61.9
Max.Price                           80.0
MPG.city                            19.0
MPG.highway                         25.0
AirBags               Driver & Passenger
DriveTrain                          Rear
Cylinders                              6
EngineSize                           3.2
Horsepower                         217.0
RPM                               5500.0
Rev.per.mile                      2220.0
Man.trans.avail                       No
Fuel.tank.capacity                  18.5
Passengers                           5.0
Length                               NaN
Wheelbase                          110.0
Width                               69.0
Turn.circle                         37.0
Rear.seat.room                       NaN
Luggage.room                        15.0
Weight          

In [24]:
# Extra: Trocando valores especificos em uma linha/coluna...

df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
     index=[7, 8, 9], columns=['max_speed', 'shield'])
df

max_speed  shield
7          1       2
8          4       5
9          7       8

In [23]:
df[df['shield']>5] = 10 # Sem o loc e repassar a coluna desejada depois do valor desejado,
df                      # o resultado troca todos os valores da linha

max_speed  shield
7          1       2
8          4       5
9         10      10

In [26]:
df.loc[df['shield']>5,['shield']]=10 # Assim é trocado o valor somente na coluna desejada
df

max_speed  shield
7          1       2
8          4       5
9          7      10

In [29]:
# N° 39

a = pd.Series(teste.columns) # Criando uma Series com os nomes de todas as colunas do DF
a

0           Manufacturer
1                  Model
2                   Type
3              Min.Price
4                  Price
5              Max.Price
6               MPG.city
7            MPG.highway
8                AirBags
9             DriveTrain
10             Cylinders
11            EngineSize
12            Horsepower
13                   RPM
14          Rev.per.mile
15       Man.trans.avail
16    Fuel.tank.capacity
17            Passengers
18                Length
19             Wheelbase
20                 Width
21           Turn.circle
22        Rear.seat.room
23          Luggage.room
24                Weight
25                Origin
26                  Make
dtype: object

In [32]:
a.replace('\.','_', inplace=True, regex=True) # Substituindo caracteres '\.' por '_' (\ para pegar qualquer espaço)
teste.columns = a # Aplicando nas colunas do DF, sem 'inplace', não funciona

In [33]:
teste.head()

Manufacturer    Model     Type  Min_Price  Price  Max_Price  MPG_city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG_highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn_circle Rear_seat_room  Luggage_room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [174]:
# N° 41

b = pd.Series([1,np.nan,3,4,np.nan,9,7])
b

0    1.0
1    NaN
2    3.0
3    4.0
4    NaN
5    9.0
6    7.0
dtype: float64

In [175]:
b.isnull().sum() # Checando se há valores nulos na Series e fazendo uma soma de quantos são nulos

2

In [36]:
a = [teste[x].isnull().sum() for x in list(teste.columns)] # Criando uma lista de nulos dentro de todas as colunas do Df e somando a quantidade desses valores
b = pd.Series(a,index=list(teste.columns)) # Criando uma Series com essa soma de nulos usando como parametro as colunas do Df
b

Manufacturer           4
Model                  1
Type                   3
Min_Price              7
Price                  2
Max_Price              5
MPG_city               9
MPG_highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev_per_mile           6
Man_trans_avail        5
Fuel_tank_capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn_circle            5
Rear_seat_room         4
Luggage_room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

In [178]:
a = [teste[x].isnull().sum() for x in teste.columns] # Alternativa sem o list
b = pd.Series(a, index = teste.columns)
b

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

In [17]:
teste.isnull().sum() # Alternativa mais simples de somar os nulos por coluna

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

In [ ]:
# N° 42

teste['Min_Price'].fillna(teste['Min_Price'].mean(),inplace=True)# Preenchendos os valores nulos nas respectivas colunas
teste['Max_Price'].fillna(teste['Max_Price'].mean(),inplace=True)# Com a média de valores das próprias colunas

In [ ]:
# Método alternativo

df['Min_Price'] = df['Min_Price'].fillna(np.mean(df['Min_Price']))
df['Max_Price'] = df['Max_Price'].fillna(np.mean(df['Max_Price']))

In [180]:
# N° 44

df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
df

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [13]:
df['a'] # Selecionando uma coluna específica de um Df

0     0
1     5
2    10
3    15
Name: a, dtype: int32

In [181]:
# N° 45

df = df[['c','b','a','d','e']] # Trocando a ordem das colunas passando uma lista com os nomes das colunas
df
# Este método é ineficiente caso o df contenha muitas colunas

c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19

In [30]:
def swapColumns(col1, col2, df):
    # Armazenando as colunas do df em uma variável
    cols = df.columns
    
    # 'Pegando'(get), os índices das colunas para a troca
    col_1 = cols.get_loc(col1)
    col_2 = cols.get_loc(col2)
    
    # trocando as duas colunas usando o índice
    df[[cols[col_1], cols[col_2]]] = df[[cols[col_2], cols[col_1]]]
    
    # Renomeando as colunas para efetivar a troca, inplace para alterar no df original
    df.rename(columns = {col1:col2, col2:col1}, inplace = True)

In [31]:
swapColumns('a', 'b', df)

In [32]:
df

c   a   b   d   e
0   2   0   1   3   4
1   7   5   6   8   9
2  12  10  11  13  14
3  17  15  16  18  19

In [40]:
def inter(x,y,df):
    lis=list(df.columns) # Criando uma lista com as colunas
    index_x=lis.index(x) # Selecionando uma coluna para ser armazenada na variável x
    index_y=lis.index(y) # Selecionando uma coluna para ser armazenada na variável y
    lis[index_x]=y # Inverter as variáveis para fazer a troca (index_x para y)
    lis[index_y]=x # Inverter as variáveis para fazer a troca (index_y para x)
    df=df[lis]
    return df

a=inter('a','b',df) # Digitar as colunas para serem trocadas
a

c   a   b   d   e
0   2   0   1   3   4
1   7   5   6   8   9
2  12  10  11  13  14
3  17  15  16  18  19

In [184]:
df.sort_index(axis=1, ascending=False) # Ordenando as colunas (axis=1) em ordem decrescente

e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15

In [16]:
# N° 48

df = pd.DataFrame(np.random.random(4), columns=['random']) # Números aleatórios de 0 à 1
df

random
0  0.257113
1  0.034564
2  0.977872
3  0.512842

In [42]:
out = df.style.format({
    'random': '{0: .2%}'.format
}) # Transformando valores de um Df em %, especificando a coluna 

out

In [208]:
# N° 50

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])
df.head()    # Lendo o csv, mostrando apenas as colunas especificadas (usecols)

Manufacturer    Model     Type  Min.Price  Max.Price
0        Acura  Integra    Small       12.9       18.8
1          NaN   Legend  Midsize       29.2       38.7
2         Audi       90  Compact       25.9       32.3
3         Audi      100  Midsize        NaN       44.6
4          BMW     535i  Midsize        NaN        NaN

In [187]:
missing = {'Manufacturer': 'missing', 'Model': 'missing', 'Type': 'missing'} # Atribuindo os novos valores a serem substituídos em colunas específicas
aux=df.fillna(value=missing) # 'Preencher' os valores nulos com 'missing'
aux.isnull().sum() # Somando a quantidade de nulos
aux                

Manufacturer    Model     Type  Min.Price  Max.Price
0         Acura  Integra    Small       12.9       18.8
1       missing   Legend  Midsize       29.2       38.7
2          Audi       90  Compact       25.9       32.3
3          Audi      100  Midsize        NaN       44.6
4           BMW     535i  Midsize        NaN        NaN
..          ...      ...      ...        ...        ...
88   Volkswagen  Eurovan      Van       16.6       22.7
89   Volkswagen   Passat  Compact       17.6       22.4
90   Volkswagen  Corrado   Sporty       22.9       23.7
91        Volvo      240  Compact       21.8       23.5
92      missing      850  Midsize       24.8       28.5

[93 rows x 5 columns]

In [211]:
# Somando os valores(strings) das colunas e retonando como um só

lis = aux.apply(lambda x: x['Manufacturer'] + x['Model'] + x['Type'],axis=1)
lis

0           AcuraIntegraSmall
1        missingLegendMidsize
2               Audi90Compact
3              Audi100Midsize
4              BMW535iMidsize
               ...           
88       VolkswagenEurovanVan
89    VolkswagenPassatCompact
90    VolkswagenCorradoSporty
91            Volvo240Compact
92          missing850Midsize
Length: 93, dtype: object

In [189]:
df =pd.DataFrame(aux.values,index=lis,columns=aux.columns) # Usando a 'soma' como index e retornando todos os valores
df

Manufacturer    Model     Type Min.Price Max.Price
AcuraIntegraSmall              Acura  Integra    Small      12.9      18.8
missingLegendMidsize         missing   Legend  Midsize      29.2      38.7
Audi90Compact                   Audi       90  Compact      25.9      32.3
Audi100Midsize                  Audi      100  Midsize       NaN      44.6
BMW535iMidsize                   BMW     535i  Midsize       NaN       NaN
...                              ...      ...      ...       ...       ...
VolkswagenEurovanVan      Volkswagen  Eurovan      Van      16.6      22.7
VolkswagenPassatCompact   Volkswagen   Passat  Compact      17.6      22.4
VolkswagenCorradoSporty   Volkswagen  Corrado   Sporty      22.9      23.7
Volvo240Compact                Volvo      240  Compact      21.8      23.5
missing850Midsize            missing      850  Midsize      24.8      28.5

[93 rows x 5 columns]

In [16]:
# Método alternativo
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=["Manufacturer", "Model", "Type", "Min.Price", "Max.Price"])
df.head()
# Lendo CSV, mas selecionando colunas especificas (usecols)

Manufacturer    Model     Type  Min.Price  Max.Price
0        Acura  Integra    Small       12.9       18.8
1          NaN   Legend  Midsize       29.2       38.7
2         Audi       90  Compact       25.9       32.3
3         Audi      100  Midsize        NaN       44.6
4          BMW     535i  Midsize        NaN        NaN

In [17]:
df.isnull().sum().sum() # 2x .sum() para a soma geral de nulos(retorna a quantidade de nulos em todo df)

20

In [18]:
df.isnull().sum() # Desta maneira, retorna os nulos especificamente em cada coluna

Manufacturer    4
Model           1
Type            3
Min.Price       7
Max.Price       5
dtype: int64

In [19]:
df.fillna('missing',inplace=True) # Preenchendo os nulos com a string 'missing'

In [22]:
df["new_index"] = df["Manufacturer"] + ' '+ df["Model"]+ ' '+ df["Type"] # Fazendo a 'soma' dos nomes das colunas para se tornar uma
# Para esse método funcionar o usecols na leitura do CSV, deve conter o nome das colunas

In [23]:
df.set_index("new_index", inplace=True) # .set_index() para 'aplicar' o novo index criado
df

Manufacturer    Model     Type Min.Price Max.Price
new_index                                                                   
Acura Integra Small              Acura  Integra    Small      12.9      18.8
missing Legend Midsize         missing   Legend  Midsize      29.2      38.7
Audi 90 Compact                   Audi       90  Compact      25.9      32.3
Audi 100 Midsize                  Audi      100  Midsize   missing      44.6
BMW 535i Midsize                   BMW     535i  Midsize   missing   missing
...                                ...      ...      ...       ...       ...
Volkswagen Eurovan Van      Volkswagen  Eurovan      Van      16.6      22.7
Volkswagen Passat Compact   Volkswagen   Passat  Compact      17.6      22.4
Volkswagen Corrado Sporty   Volkswagen  Corrado   Sporty      22.9      23.7
Volvo 240 Compact                Volvo      240  Compact      21.8      23.5
missing 850 Midsize            missing      850  Midsize      24.8      28.5

[93 rows x 5 columns]

In [108]:
# N° 51

df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,3), columns=list('abc'))
df

a   b   c
0  25  24  11
1   1  21  27
2  26  26   1
3   7   9  21
4   8   4  24
5  11  14  28
6   9   7  11
7  17  17  29
8  17  26  15
9  12  28  20

In [14]:
df.sort_values(by='a',inplace=True) 
df   # Ordem crescente usando a coluna 'a' como parâmetro

a   b   c
4   4   7   5
8   7  28   8
5   8  17   9
9   9  28  10
0  10   9  27
1  11  29  22
6  14   1   8
3  25  15  12
7  26  19  29
2  28  29  20

In [15]:
df.iloc[-5].name # Retorna o índice do quinto maior valor da coluna 'a'
# Caso contenha valores duplicados na coluna 'a', remove-los usando drop_duplicates(subset=['a'])
# subset para alterar apenas na coluna especificada

1

In [7]:
# N° 52

ser = pd.Series([7, 77, 16, 86, 60, 38, 34, 36, 83, 27, 16, 52, 50, 52, 54])
ser

0      7
1     77
2     16
3     86
4     60
5     38
6     34
7     36
8     83
9     27
10    16
11    52
12    50
13    52
14    54
dtype: int64

In [8]:
b=a[a>a.mean()] # Retorna valores que são maiores que a média
b

12    50
11    52
13    52
14    54
4     60
1     77
8     83
3     86
dtype: int64

In [9]:
b.iloc[-2] # Segundo maior valor que a média

83

In [10]:
b[b==83].index # 'pesquisando' o índice do segundo maior valor, que a média

Int64Index([8], dtype='int64')

In [46]:
# Dessa maneira retorna na ordem decrescente

b.sort_values(ascending=False,inplace=True)
b.iloc[1]

83

In [129]:
# N° 53

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df

0   1   2   3
0   19  19  34  34
1   22  33  32  15
2   15  27  12  22
3   30  24  35  35
4   34  32  37  35
5   37  38  15  25
6   32  39  26  28
7   32  22  38  15
8   16  33  14  32
9   11  33  11  19
10  17  11  28  24
11  14  35  13  38
12  17  18  14  22
13  17  24  34  36
14  27  32  26  35

In [130]:
rowsums= df.sum(axis=1) # Fazendo a soma de todos os valores das linhas
rowsums

0     106
1     102
2      76
3     124
4     138
5     115
6     125
7     107
8      95
9      74
10     80
11    100
12     71
13    111
14    120
dtype: int64

In [131]:
x = df[rowsums>100] # Selecionando as linhas onde a soma dos valores é mais de 100
x

0   1   2   3
0   19  19  34  34
1   22  33  32  15
3   30  24  35  35
4   34  32  37  35
5   37  38  15  25
6   32  39  26  28
7   32  22  38  15
13  17  24  34  36
14  27  32  26  35

In [132]:
x.iloc[-2:] # Retorna as duas últimas linhas cuja soma é maior que 100

0   1   2   3
13  17  24  34  36
14  27  32  26  35

In [133]:
# Método alternativo... Criar uma coluna com a soma das linhas

df['soma'] = df.sum(axis=1)
df

0   1   2   3  soma
0   19  19  34  34   106
1   22  33  32  15   102
2   15  27  12  22    76
3   30  24  35  35   124
4   34  32  37  35   138
5   37  38  15  25   115
6   32  39  26  28   125
7   32  22  38  15   107
8   16  33  14  32    95
9   11  33  11  19    74
10  17  11  28  24    80
11  14  35  13  38   100
12  17  18  14  22    71
13  17  24  34  36   111
14  27  32  26  35   120

In [135]:
df[df['soma']>100.].iloc[-2:] # Destacando as linha cuja a soma é maior que 100, através da coluna criada
# Retorna as duas últimas linhas cuja soma é maior que 100

0   1   2   3  soma
13  17  24  34  36   111
14  27  32  26  35   120

In [9]:
# N° 54

ser = pd.Series(np.logspace(-2, 2, 30)) # Cria matriz de valores uniformemente espaçados numa escala logarítimica.
ser

0       0.010000
1       0.013738
2       0.018874
3       0.025929
4       0.035622
5       0.048939
6       0.067234
7       0.092367
8       0.126896
9       0.174333
10      0.239503
11      0.329034
12      0.452035
13      0.621017
14      0.853168
15      1.172102
16      1.610262
17      2.212216
18      3.039195
19      4.175319
20      5.736153
21      7.880463
22     10.826367
23     14.873521
24     20.433597
25     28.072162
26     38.566204
27     52.983169
28     72.789538
29    100.000000
dtype: float64

In [10]:
low, high =ser.quantile([.05,.95])
low, high   # Armazenando em duas variáveis o valor de 5% e 95% de ser

(0.016049294076965887, 63.87667222018393)

In [13]:
ser[(ser<low)] = low # Substituindo onde no ser os valores são menores que 'low'
ser[(ser>high)] = high # Substituindo onde no ser os valores são maiores que 'high'
ser

0      0.016049
1      0.016049
2      0.018874
3      0.025929
4      0.035622
5      0.048939
6      0.067234
7      0.092367
8      0.126896
9      0.174333
10     0.239503
11     0.329034
12     0.452035
13     0.621017
14     0.853168
15     1.172102
16     1.610262
17     2.212216
18     3.039195
19     4.175319
20     5.736153
21     7.880463
22    10.826367
23    14.873521
24    20.433597
25    28.072162
26    38.566204
27    52.983169
28    63.876672
29    63.876672
dtype: float64

In [79]:
# N° 55

df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
df

0   1   2   3   4   5   6   7   8   9
0  26  27 -16   9  -7 -14  14  40  15 -10
1  44  -7 -13  48  46 -17  41   5  21   2
2  13   4   6   4  -1  36  -1   6   3  45
3 -11  48  23  47 -12  24  41  48  46  25
4  45  28   5  25   6  38 -11 -20 -13  48
5  34  11   7 -17  37  29  47 -10   6  -5
6  -2 -18 -14  41   8  13   4  18   2  49
7  49  12  42 -19  40  31  -4  44   1  43
8  -9   8  46   8  12  37  17  29  40  42
9  38  39  40  26   4  12  42  31  45 -16

In [80]:
a = np.array(df) # Transformando a atriz em um array
a = a.reshape(100) # Organizando a array numa sequência
a

array([ 26,  27, -16,   9,  -7, -14,  14,  40,  15, -10,  44,  -7, -13,
        48,  46, -17,  41,   5,  21,   2,  13,   4,   6,   4,  -1,  36,
        -1,   6,   3,  45, -11,  48,  23,  47, -12,  24,  41,  48,  46,
        25,  45,  28,   5,  25,   6,  38, -11, -20, -13,  48,  34,  11,
         7, -17,  37,  29,  47, -10,   6,  -5,  -2, -18, -14,  41,   8,
        13,   4,  18,   2,  49,  49,  12,  42, -19,  40,  31,  -4,  44,
         1,  43,  -9,   8,  46,   8,  12,  37,  17,  29,  40,  42,  38,
        39,  40,  26,   4,  12,  42,  31,  45, -16])

In [81]:
a = a[a>0] # Removendo do array os números negativos
a

array([26, 27,  9, 14, 40, 15, 44, 48, 46, 41,  5, 21,  2, 13,  4,  6,  4,
       36,  6,  3, 45, 48, 23, 47, 24, 41, 48, 46, 25, 45, 28,  5, 25,  6,
       38, 48, 34, 11,  7, 37, 29, 47,  6, 41,  8, 13,  4, 18,  2, 49, 49,
       12, 42, 40, 31, 44,  1, 43,  8, 46,  8, 12, 37, 17, 29, 40, 42, 38,
       39, 40, 26,  4, 12, 42, 31, 45])

In [82]:
a.shape # Obtendo a forma do array com os números negativos removidos

(76,)

In [83]:
b = np.sort(a) # Ordenando em ordem crescente para excluir os menores valores para formar um quadrado perfeito
b

array([ 1,  2,  2,  3,  4,  4,  4,  4,  5,  5,  6,  6,  6,  6,  7,  8,  8,
        8,  9, 11, 12, 12, 12, 13, 13, 14, 15, 17, 18, 21, 23, 24, 25, 25,
       26, 26, 27, 28, 29, 29, 31, 31, 34, 36, 37, 37, 38, 38, 39, 40, 40,
       40, 40, 41, 41, 41, 42, 42, 42, 43, 44, 44, 45, 45, 45, 46, 46, 46,
       47, 47, 48, 48, 48, 48, 49, 49])

In [84]:
b[:5]

array([1, 2, 2, 3, 4])

In [85]:
a = np.delete(a,b[:5]) # Deletando em a os valores de b (4 valores para formar um quadrado perfeito)
a

array([26, 15, 44, 48, 46, 41,  5, 21,  2, 13,  4,  6,  4, 36,  6,  3, 45,
       48, 23, 47, 24, 41, 48, 46, 25, 45, 28,  5, 25,  6, 38, 48, 34, 11,
        7, 37, 29, 47,  6, 41,  8, 13,  4, 18,  2, 49, 49, 12, 42, 40, 31,
       44,  1, 43,  8, 46,  8, 12, 37, 17, 29, 40, 42, 38, 39, 40, 26,  4,
       12, 42, 31, 45])

In [88]:
a.shape # 68 - 4 = 64, virou um quadrado perfeito 8x8

(72,)

In [90]:
a = a.reshape(8,9) # Fazendo um reshape para o quadrado perfeito
a

array([[26, 15, 44, 48, 46, 41,  5, 21,  2],
       [13,  4,  6,  4, 36,  6,  3, 45, 48],
       [23, 47, 24, 41, 48, 46, 25, 45, 28],
       [ 5, 25,  6, 38, 48, 34, 11,  7, 37],
       [29, 47,  6, 41,  8, 13,  4, 18,  2],
       [49, 49, 12, 42, 40, 31, 44,  1, 43],
       [ 8, 46,  8, 12, 37, 17, 29, 40, 42],
       [38, 39, 40, 26,  4, 12, 42, 31, 45]])

In [91]:
df = pd.DataFrame(a) # Transformando 'a' em um df
df

0   1   2   3   4   5   6   7   8
0  26  15  44  48  46  41   5  21   2
1  13   4   6   4  36   6   3  45  48
2  23  47  24  41  48  46  25  45  28
3   5  25   6  38  48  34  11   7  37
4  29  47   6  41   8  13   4  18   2
5  49  49  12  42  40  31  44   1  43
6   8  46   8  12  37  17  29  40  42
7  38  39  40  26   4  12  42  31  45

In [201]:
# N° 56

df = pd.DataFrame(np.arange(25).reshape(5, -1))
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [202]:
# Trocando as linhas de um Df
def swap_rows(df, row1, row2):
    df.iloc[row1], df.iloc[row2] =  df.iloc[row2].copy(), df.iloc[row1].copy()
    return df

In [203]:
swap_rows(df, 4, 3)

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  20  21  22  23  24
4  15  16  17  18  19

In [48]:
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [59]:
def invert(x,y,df):
    aux = df.copy()
    val_x = df.iloc[x].name
    val_y= df.iloc[y].name
    aux.iloc[x] =df.iloc[val_y]
    aux.iloc[y] =df.iloc[val_x]
    return aux

df = invert(2,3,df)
df

0   1   2   3   4
0   0   2   1   3   4
1  10  12  11  13  14
2  15  17  16  18  19
3   5   7   6   8   9
4  20  22  21  23  24

In [136]:
# N° 57

df = pd.DataFrame(np.arange(25).reshape(5, -1))
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [137]:
df.sort_index(ascending=False) # Retorna a ordem decrescente dos índices

0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

In [142]:
# N° 59

df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
df

0   1   2   3
0  40  99  45  56
1  95  40  58  93
2  77  97  62  53
3  18  21  32  43
4  29  77   4  50
5  32  50  17  20
6  90  16   6  79
7  55  55  35  15
8   4  90  34  90
9  48  39  28  72

In [143]:
a=[df[x].sum() for x in df.columns]
np.argmax(a)

1

In [144]:
df.apply(np.argmax, axis=1).value_counts().index[0]

1

In [146]:
# N° 60

df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))
aux = np.array(df)
aux

array([[68,  2, 61, 81],
       [72, 39, 98, 57],
       [87, 13, 12, 93],
       [47, 82, 23, 90],
       [23, 48, 38, 59],
       [25, 30,  3, 86],
       [93, 69, 61, 27],
       [54, 73, 12, 32],
       [96, 40, 68, 85],
       [30,  4, 74, 57]])

In [147]:
mx_vetor_1_dif_todos = aux[0] - aux
a = (mx_vetor_1_dif_todos@mx_vetor_1_dif_todos.T).diagonal()**(0.5)
a

array([  0.        ,  57.70615219,  55.01817881,  91.46584062,
        71.79136438,  77.60154638,  89.61026727, 100.19481024,
        47.88527958,  46.8294779 ])

In [148]:
lin=[]
dist=[]
for i in range(len(aux)):
    dif_p =(aux[i,:]-aux)# distancia entre ponto da linha i x todas as linhas (10x4)
    som_prod=(dif_p@(dif_p.T))# calc soma do produto de cada linha utilizando produto de matrizes: (10x4)@(4x10)-> 10x10
    mod= som_prod.diagonal()**(0.5) # diagonal igual ao modulo ao quadrado de cada linha
    mod = np.delete(mod,[i]) # retirando o valor 0 que é a dinstancia de um ponto pra ele mesmo
    lin.append(np.argmin(mod))

In [154]:
for x in lin:
    print(df.index[x])


i
h
a
d
e
e
b
e
b
a


In [156]:
df['nearest_row']= list(map(lambda x: df.index[x] ,lin))
df

p   q   r   s nearest_row
a  68   2  61  81           i
b  72  39  98  57           h
c  87  13  12  93           a
d  47  82  23  90           d
e  23  48  38  59           e
f  25  30   3  86           e
g  93  69  61  27           b
h  54  73  12  32           e
i  96  40  68  85           b
j  30   4  74  57           a

In [92]:
# N° 62

df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
df

0   1   2   3   4   5   6   7   8   9
0  24  96  66  51  91  22   3  99  82  23
1  71  40  58  87  34  76  78  80  27  58
2  91  67  32  94  17  35  78  79  95   7
3  35  20  44  28  26  13  43  86  36  11
4  72  24  45  66  50  53  64  71   3  98
5  30  58  90  47  28  89  92  71  30  16
6  95   7  95  61  42   2  94  88  66  88
7  38  35  23  51  89  22  22  65  64  95

In [94]:
min_by_max = np.min(df, axis=1)/np.max(df, axis=1) # Retornando o mínimo pelo máximo de cada linha
min_by_max

0    0.030303
1    0.310345
2    0.073684
3    0.127907
4    0.030612
5    0.173913
6    0.021053
7    0.231579
dtype: float64

In [96]:
df['min_by_max'] = min_by_max # Criando uma coluna com os valores
df

0   1   2   3   4   5   6   7   8   9  min_by_max
0  24  96  66  51  91  22   3  99  82  23    0.030303
1  71  40  58  87  34  76  78  80  27  58    0.310345
2  91  67  32  94  17  35  78  79  95   7    0.073684
3  35  20  44  28  26  13  43  86  36  11    0.127907
4  72  24  45  66  50  53  64  71   3  98    0.030612
5  30  58  90  47  28  89  92  71  30  16    0.173913
6  95   7  95  61  42   2  94  88  66  88    0.021053
7  38  35  23  51  89  22  22  65  64  95    0.231579

In [145]:
# N° 63

df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
df

0   1   2   3   4   5   6   7   8   9
0  34  25  76  41  44  79  10  91  70  31
1  54  82  75  89  51  99  23  77   8  41
2  91  26  20  66   3  62  72   1  48  37
3  73  23  53  82  32  52  26  87  86  38
4  43  37  30  19   4  47  42  77   4  22
5  70  66  59  51  38  70  95  16  93  20
6  66  43  11  42  75  17  12  97  22  12
7  63  49  33  83  64  59  15  65  68  86

In [146]:
# Ordenando os valores pelas linhas, selecionando o penúltimo valor(-2)

x = df.apply(lambda x: x.sort_values().unique()[-2], axis=1)
df['penultimate'] = x 
df

0   1   2   3   4   5   6   7   8   9  penultimate
0  34  25  76  41  44  79  10  91  70  31           79
1  54  82  75  89  51  99  23  77   8  41           89
2  91  26  20  66   3  62  72   1  48  37           72
3  73  23  53  82  32  52  26  87  86  38           86
4  43  37  30  19   4  47  42  77   4  22           47
5  70  66  59  51  38  70  95  16  93  20           93
6  66  43  11  42  75  17  12  97  22  12           75
7  63  49  33  83  64  59  15  65  68  86           83

In [155]:
# N° 64

df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
df

0   1   2   3   4   5   6   7   8   9
0  13  94  24  25   2  66  80  76  48  71
1  63  19  19  28  12  59  19  39  63   7
2  75  48  45  38  43  68  88   5  22  83
3  23  53  98  82   2  65  48  72  95  89
4  82  84  83  33  51  80  66  18  88  14
5  55  25  93  72  74  96  25  19  54  25
6  31  98  57  19  74  57  36  57  74  28
7  46  89  63  14  48  48  65  78  20  84

In [156]:
df1 = df.apply(lambda x: ((x-np.mean(x))/np.std(x)))
df1 # Normalizando, subtraindo os valores por sua média e dividindo pelo desvio padrão(np.std), linha a linha

0         1         2         3         4         5         6  \
0 -1.531225  1.022381 -1.293663 -0.597301 -1.307049 -0.099107  1.120138   
1  0.625430 -1.512448 -1.472100 -0.468155 -0.946484 -0.603653 -1.446187   
2  1.143027 -0.532314 -0.544231 -0.037668  0.171269  0.045049  1.456705   
3 -1.099894 -0.363326  1.347194  1.856476 -1.307049 -0.171185 -0.226131   
4  1.444959  0.684404  0.811885 -0.252911  0.459721  0.909984  0.531145   
5  0.280365 -1.309662  1.168758  1.425989  1.289021  2.063231 -1.193762   
6 -0.754829  1.157572 -0.115984 -0.855593  1.289021 -0.747808 -0.730982   
7 -0.107833  0.853392  0.098140 -1.070837  0.351551 -1.396510  0.489074   

          7         8         9  
0  1.117246 -0.384687  0.641895  
1 -0.238102  0.192343 -1.326070  
2 -1.483556 -1.384871  1.010888  
3  0.970722  1.423340  1.195385  
4 -1.007353  1.154060 -1.110824  
5 -0.970722 -0.153875 -0.772580  
6  0.421257  0.615498 -0.680332  
7  1.190508 -1.461809  1.041638

In [157]:
# Normalizando subtraindo o máximo pelos valores do df e dividindo pelo máximo/mínimo, para possuir valores enter 0 e 1

df2 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2))
df2

0     1     2     3     4     5     6     7     8     9
0  1.00  0.05  0.94  0.84  1.00  0.62  0.12  0.03  0.63  0.22
1  0.28  1.00  1.00  0.79  0.86  0.77  1.00  0.53  0.43  1.00
2  0.10  0.63  0.67  0.65  0.43  0.58  0.00  1.00  0.97  0.07
3  0.86  0.57  0.00  0.00  1.00  0.65  0.58  0.08  0.00  0.00
4  0.00  0.18  0.19  0.72  0.32  0.33  0.32  0.82  0.09  0.91
5  0.39  0.92  0.06  0.15  0.00  0.00  0.91  0.81  0.55  0.78
6  0.74  0.00  0.52  0.93  0.00  0.81  0.75  0.29  0.28  0.74
7  0.52  0.11  0.44  1.00  0.36  1.00  0.33  0.00  1.00  0.06

In [127]:
# N° 65

df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
df

0   1   2   3   4   5   6   7   8   9
0  33  54  34  14  48  16  49  69   4  63
1  24  53  18  38  56  36  69  91  11   2
2  45  48  22  23  99  25  20  39  56  29
3  34   2  22  63  59  53  28  55  89  84
4  94  20  51  98  15  75  11  30   1  94
5  74  84  46  88  79  28  34  56  36  78
6  23  83  77  26  46  31  94  84  16  90
7   1  13  17  35  89   4  47  36  53  23

In [130]:
# selecionando todas as linhas com todas as colunas
# fazendo a correlação com a próxima linha (i+1) em todas as colunas (:)
# laço for 'varrendo' todo o df (-1 para parar na última linha, já que não tem uma próxima linha para correlação)
[(df.iloc[i,:]).corr(df.iloc[i+1,:]) for i in range(len(df)-1)]

[0.4775183378730032,
 0.13069622638544592,
 0.1681666523519097,
 0.1502331235079617,
 0.3572578562339337,
 0.020242312770622096,
 -0.030263311579465216]

In [158]:
# N° 66

df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))
aux=np.array(df)
aux

array([[65, 89, 96, 86, 16, 48, 48, 28, 47, 48],
       [ 5, 70, 81, 51,  9, 69, 44,  7, 69, 85],
       [95, 76, 82, 50, 51, 39, 62, 83, 81, 55],
       [ 6, 23, 73, 15, 39, 17, 39, 29, 52, 56],
       [24,  6, 53, 89, 20, 21,  7,  5, 23, 74],
       [88, 95, 15, 87, 69, 87,  7, 63, 62, 62],
       [30, 38, 74, 25, 93, 12, 54, 87, 32,  5],
       [34, 72, 95, 86, 29, 38, 57, 59, 71, 32],
       [21, 15, 68, 81, 95, 87, 14,  1, 76,  9],
       [74, 57, 10, 13, 98, 50, 76, 57,  5, 42]])

In [159]:
dim =np.diag_indices(10)
aux[dim]=0
aux # Cria uma diagonal de zeros

array([[ 0, 89, 96, 86, 16, 48, 48, 28, 47, 48],
       [ 5,  0, 81, 51,  9, 69, 44,  7, 69, 85],
       [95, 76,  0, 50, 51, 39, 62, 83, 81, 55],
       [ 6, 23, 73,  0, 39, 17, 39, 29, 52, 56],
       [24,  6, 53, 89,  0, 21,  7,  5, 23, 74],
       [88, 95, 15, 87, 69,  0,  7, 63, 62, 62],
       [30, 38, 74, 25, 93, 12,  0, 87, 32,  5],
       [34, 72, 95, 86, 29, 38, 57,  0, 71, 32],
       [21, 15, 68, 81, 95, 87, 14,  1,  0,  9],
       [74, 57, 10, 13, 98, 50, 76, 57,  5,  0]])

In [160]:
flip_aux=np.flip(aux,axis=1)
flip_aux[dim]=0
aux = np.flip(flip_aux,axis=1) # Cria duas diagonais de zeros, fazendo um X de zeros
aux

array([[ 0, 89, 96, 86, 16, 48, 48, 28, 47,  0],
       [ 5,  0, 81, 51,  9, 69, 44,  7,  0, 85],
       [95, 76,  0, 50, 51, 39, 62,  0, 81, 55],
       [ 6, 23, 73,  0, 39, 17,  0, 29, 52, 56],
       [24,  6, 53, 89,  0,  0,  7,  5, 23, 74],
       [88, 95, 15, 87,  0,  0,  7, 63, 62, 62],
       [30, 38, 74,  0, 93, 12,  0, 87, 32,  5],
       [34, 72,  0, 86, 29, 38, 57,  0, 71, 32],
       [21,  0, 68, 81, 95, 87, 14,  1,  0,  9],
       [ 0, 57, 10, 13, 98, 50, 76, 57,  5,  0]])

In [164]:
# Método Alternativo
# Usando duas variaveis (i,j) para 'varrer' o df

for i in range(len(df)):
    for j in range(len(df)):
        if i==j: # Se i=j, usar iloc para pegar o índice da linha e coluna
            df.iloc[i,j]=0
            df.iloc[::-1].iloc[i,j]=0 # invertendo o iloc para fazer o outro 'X de zeros', iloc[::-1]
df

0   1   2   3   4   5   6   7   8   9
0   0  89  96  86  16  48  48  28  47   0
1   5   0  81  51   9  69  44   7   0  85
2  95  76   0  50  51  39  62   0  81  55
3   6  23  73   0  39  17   0  29  52  56
4  24   6  53  89   0   0   7   5  23  74
5  88  95  15  87   0   0   7  63  62  62
6  30  38  74   0  93  12   0  87  32   5
7  34  72   0  86  29  38  57   0  71  32
8  21   0  68  81  95  87  14   1   0   9
9   0  57  10  13  98  50  76  57   5   0

In [21]:
# N° 67

df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})
df

col1      col2  col3
0   apple  0.351186     6
1  banana  0.904261    14
2  orange  0.825091     0
3   apple  0.909926     8
4  banana  0.076418     5
5  orange  0.479460     7
6   apple  0.068605     0
7  banana  0.923381     6
8  orange  0.496282     8

In [22]:
aux=df[df['col1']=='apple'] # Destaca os valores de 'apple'
aux

col1      col2  col3
0  apple  0.351186     6
3  apple  0.909926     8
6  apple  0.068605     0

In [23]:
df.query('col1 == "apple"') # Usando método query

col1      col2  col3
0  apple  0.351186     6
3  apple  0.909926     8
6  apple  0.068605     0

In [67]:
group_aux = aux.groupby(by=['col2','col3'])
pd.DataFrame(group_aux.groups)

0.222407 0.278654 0.280347
        9        14       12
0        6        3        0

In [131]:
# N° 68

df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
df

fruit    rating  price
0   apple  0.045793      8
1  banana  0.341050     12
2  orange  0.263999      8
3   apple  0.621695     14
4  banana  0.695490      4
5  orange  0.682343      1
6   apple  0.147951      3
7  banana  0.164315      2
8  orange  0.963897      1

In [134]:
# Retorna o segundo maior valor em 'rating', para banana
# agrupando pela coluna 'fruit', 'pegando' os valores de 'banana', ordenando os valores de 'rating'...
# e selecionando o segundo maior valor [iloc[-2]]

df.groupby(by=['fruit']).get_group('banana').sort_values('rating').iloc[-2,1]

0.3410503317277469

In [135]:
# N° 69

df.groupby('fruit',as_index=False).mean() # Retorna a média de todos os valores númericos através da coluna 'fruit'

fruit    rating     price
0   apple  0.271813  8.333333
1  banana  0.400285  6.000000
2  orange  0.636746  3.333333

In [2]:
# N° 70

df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3, # '*3', para repetir 3x as frutas
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})
df1

fruit  weight  price
0   apple    high     11
1  banana  medium     13
2  orange     low      3
3   apple    high      6
4  banana  medium      6
5  orange     low      1
6   apple    high      5
7  banana  medium      8
8  orange     low     11

In [3]:
df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})
df2

pazham  kilo  price
0   apple  high     14
1  orange   low     10
2    pine  high      4
3   apple   low      6
4  orange  high      7
5    pine   low     10

In [4]:
pd.merge(df1, df2, how='inner', left_on=['fruit', 'weight'], right_on=['pazham', 'kilo'],suffixes=['_1', '_2'])

fruit weight  price_1  pazham  kilo  price_2
0   apple   high       11   apple  high       14
1   apple   high        6   apple  high       14
2   apple   high        5   apple  high       14
3  orange    low        3  orange   low       10
4  orange    low        1  orange   low       10
5  orange    low       11  orange   low       10

In [5]:
# N° 71

df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'kilo': ['high', 'medium', 'low'] * 3,})
df1

fruit    kilo
0   apple    high
1  banana  medium
2  orange     low
3   apple    high
4  banana  medium
5  orange     low
6   apple    high
7  banana  medium
8  orange     low

In [6]:
df2 = pd.DataFrame({'fruit': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,})
df2

fruit  kilo
0   apple  high
1  orange   low
2    pine  high
3   apple   low
4  orange  high
5    pine   low

In [7]:
print(df1[~df1.isin(df2).all(1)]) #.all??????

    fruit    kilo
1  banana  medium
2  orange     low
3   apple    high
4  banana  medium
5  orange     low
6   apple    high
7  banana  medium
8  orange     low


In [8]:
df1[df1['fruit'].isin(df2['fruit'])].index # Retorna os índices onde os valores são iguais nos dois df's

Int64Index([0, 2, 3, 5, 6, 8], dtype='int64')

In [11]:
df1 = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})

df2= pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})
df2

fruit1  fruit2
0  orange  orange
1   apple  banana
2   apple   apple
3  banana   apple
4  banana  orange
5  orange  orange
6  orange  banana
7  orange  banana
8  orange  orange
9  banana  orange

In [12]:
np.where(df1.fruit1==df2.fruit1) 
# funciona quando dataframes comparados possuem as mesmas features(com mesmo nome), incluindo as não comparadas

(array([2, 3, 6, 7, 9], dtype=int64),)

In [24]:
# N° 72

df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))
df

a   b   c   d
0  71  49  78  74
1  87  95   1   8
2  68   5  90  44
3  40  97  29  50
4  67  85   4  63

In [26]:
df['a'].shift(1)

0     NaN
1    71.0
2    87.0
3    68.0
4    40.0
Name: a, dtype: float64

In [27]:
df['b'].shift(-1)

0    95.0
1     5.0
2    97.0
3    85.0
4     NaN
Name: b, dtype: float64

In [29]:
# N° 73

df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))
df

a  b  c  d
0  9  3  8  9
1  9  3  4  4
2  7  9  8  3
3  4  6  6  2
4  9  3  4  4

In [30]:
df['a'].value_counts() # Retorna a frequência de valores da coluna 'a'

9    3
7    1
4    1
Name: a, dtype: int64

In [31]:
df.melt()['value'].value_counts() # Retorna a frequencia de valores de todo o df

9    5
4    5
3    4
6    2
8    2
7    1
2    1
Name: value, dtype: int64

In [33]:
pd.value_counts(df.values.ravel()) # Método alternativo de fazer a frequencia em todo df

9    5
4    5
3    4
8    2
6    2
7    1
2    1
dtype: int64

In [32]:
# N° 74